### ISSUE TITLE
Dropdown image

### ISSUE THREAD

**Issue by LcKoh0830** [technologiescollege/Blockly-at-rduino#166]
Hi, is that possible we can add image into the dropdown option in block?

**Comment by SebCanet** [comment]
Hi,
it's possible, you have example in Blockly's official guide: [https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#image_dropdowns](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#image_dropdowns)

Enjoy.

**Comment by LcKoh0830** [comment]
@SebCanet Hi, thanks for the answer. Is it possible we can add the function (dropdown with image) into Blockly@duino? If yes, can you tell me how?

**Comment by SebCanet** [comment]
@LcKoh0830 Hi,
really sorry, I discover just now your answer...
Where would you add this function?

**Comment by LcKoh0830** [comment]
Hi, I had already forgot where should the function added.
But I think is the field_dropdown function do not have the function to handle image.
Blockly's official field_dropdown.js have the function to handle image, the blockly js here had been compressed, so I am not sure how to add it.

**Comment by SebCanet** [comment]
Maybe it will be a function for the new BlocklyDuino: [https://github.com/BlocklyDuino/BlocklyDuino-v2](https://github.com/BlocklyDuino/BlocklyDuino-v2)
I'm working on it to reboot my soft because I made too many modification in original Blockly code, and I cannot update it anymore... So start back with their new features.
