### ISSUE TITLE
Soucis avec la dernière version

### ISSUE THREAD

**Issue by jbet** [technologiescollege/Blockly-at-rduino#17]
J'ai téléchargé la dernière version à partir du Github, et voilà le résultat :
![selection_219](https://cloud.githubusercontent.com/assets/5906988/14628537/5a5870fe-05ff-11e6-9035-2886b484f593.png)

Il n'y a plus de correspondance entre les blocs et le code.

Bon courage.

**Comment by SebCanet** [comment]
Avec le typag intégré (et obligatoire maintenant, ça marche) 
![capture](https://cloud.githubusercontent.com/assets/6362199/14771339/504049d8-0a88-11e6-9114-115ee2903a16.JPG)

**Comment by technoman72** [comment]
Manque la traduction de NUMBER en nombre ou entier ? 

Envoyé depuis un mobile Samsung.

-------- Message d'origine --------
De : SebCanet notifications@github.com 
Date : 25/04/2016  01:52  (GMT+01:00) 
À : technologiescollege/Blockly-at-rduino Blockly-at-rduino@noreply.github.com 
Objet : Re: [technologiescollege/Blockly-at-rduino] Soucis avec la dernière version (#17) 

Avec le typag intégré (et obligatoire maintenant, ça marche) 

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub

Manque la traduction de NUMBER en nombre ou entier ?�
Envoyé depuis un mobile Samsung.
-------- Message d'origine --------
De : SebCanet notifications@github.com
Date : 25/04/2016 01:52 (GMT+01:00)
À : technologiescollege/Blockly-at-rduino Blockly-at-rduino@noreply.github.com
Objet : Re: [technologiescollege/Blockly-at-rduino] Soucis avec la dernière version (#17)
Avec le typag intégré (et obligatoire maintenant, ça marche)
https://cloud.githubusercontent.com/assets/6362199/14771339/504049d8-0a88-11e6-9114-115ee2903a16.JPG https://cloud.githubusercontent.com/assets/6362199/14771339/504049d8-0a88-11e6-9114-115ee2903a16.JPG
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or https://github.com/technologiescollege/Blockly-at-rduino/issues/17#issuecomment-214068312 view it on GitHub
https://github.com/notifications/beacon/ALcw4Dw5wPpib3EzbwSYbYPXw3p3tUcyks5p7AIsgaJpZM4IKXX3.gif

**Comment by SebCanet** [comment]
trad faite mais pas automatique encore.

**Comment by jbet** [comment]
OK j'ai essayé, et cela fonctionne.

Mais cela aurait été mieux de pouvoir faire un #define , comme je l'ai mis sur le github.

Pour résoudre le problème d'algorigramme, algorithme au brevet, je vais leur apprendre les algorigrammes, et on fera la traduction en algorithme, avec votre logiciel.

Bonne soirée.

----- Mail original -----
De: "SebCanet" notifications@github.com
À: "technologiescollege/Blockly-at-rduino" Blockly-at-rduino@noreply.github.com
Cc: "jbet" jb.etieve@free.fr, "Author" author@noreply.github.com
Envoyé: Lundi 25 Avril 2016 01:52:13
Objet: Re: [technologiescollege/Blockly-at-rduino] Soucis avec la dernière version (#17)

Avec le typag intégré (et obligatoire maintenant, ça marche) 
capture
