### ISSUE TITLE
i can't found blocks !!!

### ISSUE THREAD

**Issue by hamam1** [technologiescollege/Blockly-at-rduino#79]
![screenshot-2017-9-29 blockly rduino](https://user-images.githubusercontent.com/32391090/31036164-600c29e8-a56b-11e7-96ce-1786b7ef9351.png)

**Comment by SebCanet** [comment]
First you choose your card, then select your level of 'difficulty', from 0 to ALL.
You click on "configure blocks", blocks from difficulty level.
That's all.

**Comment by hamam1** [comment]
Thank you very much <3 <3 <3 <3 <3 
please can you help me how i can use "arduino  ir remote control "
and how i can make new block 
sincerely <3 <3 <3 <3 <3

**Comment by SebCanet** [comment]
For the arduino ir remote control, I don't know because I'm not the creator of this blocks....
To create block, you have french doc there: [http://info.technologiescollege.fr/wiki/doku.php/fr/arduino/blockly_rduino/creerblocsmultiling](http://info.technologiescollege.fr/wiki/doku.php/fr/arduino/blockly_rduino/creerblocsmultiling)
and english version (but not updated...if you want to help me !?): [http://info.technologiescollege.fr/wiki/doku.php/en/blockly_rduino/create_blocks](http://info.technologiescollege.fr/wiki/doku.php/en/blockly_rduino/create_blocks)

Hope it can help.

**Comment by hamam1** [comment]
there are any vedio  can help me to create a new block 
becuse i am from egypt and iam not good in english <3

**Comment by SebCanet** [comment]
I never made video to explain, it would be too much long. And it would be with many comments (in French or english), so you will have the same pb. Maybe you could try by online translation.
